### ISSUE TITLE
Searching for items causes tab name to revert to icons

### ISSUE THREAD

**Issue by hjdarnel** [Psyda/bank-tab-names#1]
Hey,

I have some simple tabs set up with just text and color changing. When I search the bank, these revert to the icons like in the vanilla client. I wasn't sure if this is a tracked issue. I'm happy to give more information!

Thanks!

**Comment by Psyda** [comment]
Thanks for that, I've made note of it and will look into it later this week. For now, I believe you might be able to get it working more consistently with a different default tab-mode in the bank settings. Setting it to numerical seems to be the most stable. Normally I would have to disable the item image and then convert them back to text before styling them.

**Comment by septicsalmon** [comment]
I'm still having this issue and setting it to both digit or roman numeral doesnt really make it any better.

Any update on how this is coming along?

**Comment by Jin-Jiyunsun** [comment]
Any possibility of an update on this?

**Comment by Beagon** [comment]
This is still an issue, can I assume there is no development on this plugin anymore?

@Psyda
