### ISSUE TITLE
[Request] Add ability to disable plugin for specific tabs

### ISSUE THREAD

**Issue by Nick2bad4u** [Psyda/bank-tab-names#4]
For example,

You should be able to disable tab 1 and it will go back to its default state, while still using the plugin for Tab 2-8

**Comment by Psyda** [comment]
There is already checkbox for that!

**Comment by Nick2bad4u** [comment]
> There is already checkbox for that!
> 
> ![85232804-fb10b600-b3cf-11ea-92eb-f774e07e67c9 1](https://user-images.githubusercontent.com/17040097/235329863-3720f085-5e48-4c45-a0d1-6e81c56b405e.png)

I'm referring to ALL the tabs, not just tab 0.

**Comment by Psyda** [comment]
@Beagon the legend completed this one!
